### PR TITLE
Take a big Data Dump into the project.

### PR DESCRIPTION
**Pull request by ajmyers01**
Uploading the big ole data dump given to us by a community member
for us to use as seed data. Also added something to the gitignore.

### CODE REVIEW

**Comment by MickeyUK** [comment]
I don't think this is a good idea. There is identifiable information in that JSON and this is a public repo. The data dump is just a learning tool for us so that we can pick it apart, see what a lot of briefs look like and then create an algorithm for making briefs with what we've learnt.

The dump could be put somewhere the team can access privately though, maybe on a Google Drive setup for the team?

**Review by Araz0 — APPROVED** [review]
I dont see any issues with it.... i dont see any names, birth dates, locations, or health information...
the rest depends on if the source allows using it for learning or not (@ajmyers01 can you dm me the source pls ? (i might use it for another project if i can)). 
other than that. im good with it for learning perpeses!!

**Comment by MickeyUK** [comment]
It has e-mail addresses in there. Even if they shared those e-mail addresses publically, we're getting in to data protection law territory here for no reason. Plus it's data that has been scraped without permission...and whilst there are [no governing laws](https://www.twobirds.com/en/insights/2021/global/legal-weapons-in-the-fight-against-data-scraping) on that kind of thing, it's a potential fight we don't need to have lol. Plus it's just not very professional.

We just don't need to push the JSON, we won't be serving any of it, it's not part of the project.

**Comment by Araz0** [comment]
> It has e-mail addresses in there. Even if they shared those e-mail addresses publically, we're getting in to data protection law territory here for no reason. Plus it's data that has been scraped without permission...and whilst there are [no governing laws](https://www.twobirds.com/en/insights/2021/global/legal-weapons-in-the-fight-against-data-scraping) on that kind of thing, it's a potential fight we don't need to have lol. Plus it's just not very professional.
> 
> We just don't need to push the JSON, we won't be serving any of it, it's not part of the project.

I totaly understand what you saying.... an easy fix for it would be just GREP'ing the file and replace any email with a generic one like my@mail.com or something...

**Comment by MickeyUK** [comment]
That wasn't my only reservation, ha. If you see what I said in the Discord about how the algorithm will work, you'll further see how we don't need the json at all, or even need to advertise we have it.

You're the PM though, if you want to push it, we can push it. 😅

**Review by MickeyUK — APPROVED** [review]
Strongly reconsider this though, folks. :P

**Comment by ajmyers01** [comment]
@MickeyUK  has some good points both here and in discord. I'll close this and if you want the data it's in the collab in discord.

**Pull request closed without merging**
